<?php
namespace app\api\model;

use think\Model;

class Member extends Model
{
    protected $table = "tb_member";
    protected $resultSetType = 'collection';

    public function validateFailException($fail = true)
    {
        return parent::validateFailException($fail); // TODO: Change the autogenerated stub
    }

    //个人信息
    public function user($uid)
    {
        return self::get(['member_id'=>$uid])  -> toArray();

    }
}